# Generated by Django 4.2.30 on 2026-06-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='pending_leave_request',
            field=models.BooleanField(default=False),
        ),
    ]
